// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CrazyPOS.Server.Models;

public partial class Category
{
    public long Categoryid { get; set; }

    public string Name { get; set; }
}