// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace CrazyPOS.Server.Models;

public partial class crazypos_devContext : DbContext
{
    public crazypos_devContext(DbContextOptions<crazypos_devContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<HoldOrder> HoldOrders { get; set; }

    public virtual DbSet<HoldOrderItem> HoldOrderItems { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<Inventory> Inventories { get; set; }

    public virtual DbSet<InventoryAudit> InventoryAudits { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Category>(entity =>
        {
            entity.ToTable("categories");

            entity.Property(e => e.Categoryid).HasColumnName("categoryid");
            entity.Property(e => e.Name).HasColumnName("name");
        });

        modelBuilder.Entity<HoldOrder>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__hold_ord__3213E83F302593FA");

            entity.ToTable("hold_order");

            entity.HasIndex(e => e.Status, "IX_hold_order_status");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CustomerName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("customer_name");
            entity.Property(e => e.OrderDate)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnType("datetime")
                .HasColumnName("order_date");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("Active")
                .HasColumnName("status");
            entity.Property(e => e.TotalAmount)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("total_amount");
        });

        modelBuilder.Entity<HoldOrderItem>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__hold_ord__3213E83FA937D1E5");

            entity.ToTable("hold_order_item");

            entity.HasIndex(e => e.HoldOrderId, "IX_hold_order_item_hold_order_id");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.HoldOrderId).HasColumnName("hold_order_id");
            entity.Property(e => e.Price)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("price");
            entity.Property(e => e.Productid).HasColumnName("productid");
            entity.Property(e => e.Quantity).HasColumnName("quantity");

            entity.HasOne(d => d.HoldOrder).WithMany(p => p.HoldOrderItems)
                .HasForeignKey(d => d.HoldOrderId)
                .HasConstraintName("FK_hold_order_item_hold_order");

            entity.HasOne(d => d.Product).WithMany(p => p.HoldOrderItems)
                .HasForeignKey(d => d.Productid)
                .HasConstraintName("FK_hold_order_item_product");
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.ToTable("product");

            entity.Property(e => e.Productid).HasColumnName("productid");
            entity.Property(e => e.Barcode).HasColumnName("barcode");
            entity.Property(e => e.Categoryid).HasColumnName("categoryid");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.Image).HasColumnName("image");
            entity.Property(e => e.Imgextension)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("imgextension");
            entity.Property(e => e.Name)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("name");
            entity.Property(e => e.Price)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("price");
            entity.Property(e => e.Stock).HasColumnName("stock");
        });

        modelBuilder.Entity<Inventory>(entity =>
        {
            entity.ToTable("inventory");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Productid).HasColumnName("productid");
            entity.Property(e => e.Quantity).HasColumnName("quantity");
            entity.Property(e => e.MovementType).HasColumnName("movement_type");
            entity.Property(e => e.Reference).HasColumnName("reference");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.Notes).HasColumnName("notes");

            entity.HasOne(d => d.Product).WithMany(p => p.Inventories)
                .HasForeignKey(d => d.Productid)
                .HasConstraintName("FK_inventory_product");
        });

        modelBuilder.Entity<InventoryAudit>(entity =>
        {
            entity.ToTable("inventory_audit");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Inventoryid).HasColumnName("inventoryid");
            entity.Property(e => e.ChangeAmount).HasColumnName("change_amount");
            entity.Property(e => e.ChangeDate)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnType("datetime")
                .HasColumnName("change_date");

            entity.HasOne(d => d.Inventory).WithMany(p => p.InventoryAudits)
                .HasForeignKey(d => d.Inventoryid)
                .HasConstraintName("FK_inventory_audit_inventory");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}