// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace CrazyPOS.Server.Models;

public partial class crazypos_devContext : DbContext
{
    public crazypos_devContext(DbContextOptions<crazypos_devContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<HoldOrder> HoldOrders { get; set; }

    public virtual DbSet<HoldOrderItem> HoldOrderItems { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<Inventory> Inventories { get; set; }

    public virtual DbSet<InventoryAudit> InventoryAudits { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserSession> UserSessions { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<SalesTransaction> SalesTransactions { get; set; }

    public virtual DbSet<TransactionItem> TransactionItems { get; set; }

    public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }

    public virtual DbSet<BarcodeMapping> BarcodeMappings { get; set; }

    public virtual DbSet<PaymentTenderLog> PaymentTenderLogs { get; set; }

    public virtual DbSet<DailySalesSummary> DailySalesSummaries { get; set; }

    public virtual DbSet<Receipt> Receipts { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Permission> Permissions { get; set; }

    public virtual DbSet<RolePermission> RolePermissions { get; set; }

    public virtual DbSet<AuditLog> AuditLogs { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Category>(entity =>
        {
            entity.ToTable("categories");

            entity.Property(e => e.Categoryid).HasColumnName("categoryid");
            entity.Property(e => e.Name).HasColumnName("name");
        });

        modelBuilder.Entity<HoldOrder>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__hold_ord__3213E83F302593FA");

            entity.ToTable("hold_order");

            entity.HasIndex(e => e.Status, "IX_hold_order_status");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CustomerName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("customer_name");
            entity.Property(e => e.OrderDate)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnType("datetime")
                .HasColumnName("order_date");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("Active")
                .HasColumnName("status");
            entity.Property(e => e.TotalAmount)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("total_amount");
        });

        modelBuilder.Entity<HoldOrderItem>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__hold_ord__3213E83FA937D1E5");

            entity.ToTable("hold_order_item");

            entity.HasIndex(e => e.HoldOrderId, "IX_hold_order_item_hold_order_id");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.HoldOrderId).HasColumnName("hold_order_id");
            entity.Property(e => e.Price)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("price");
            entity.Property(e => e.Productid).HasColumnName("productid");
            entity.Property(e => e.Quantity).HasColumnName("quantity");

            entity.HasOne(d => d.HoldOrder).WithMany(p => p.HoldOrderItems)
                .HasForeignKey(d => d.HoldOrderId)
                .HasConstraintName("FK_hold_order_item_hold_order");

            entity.HasOne(d => d.Product).WithMany(p => p.HoldOrderItems)
                .HasForeignKey(d => d.Productid)
                .HasConstraintName("FK_hold_order_item_product");
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.ToTable("product");

            entity.Property(e => e.Productid).HasColumnName("productid");
            entity.Property(e => e.Barcode).HasColumnName("barcode");
            entity.Property(e => e.Categoryid).HasColumnName("categoryid");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.Image).HasColumnName("image");
            entity.Property(e => e.Imgextension)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("imgextension");
            entity.Property(e => e.Name)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("name");
            entity.Property(e => e.Price)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("price");
            entity.Property(e => e.Stock).HasColumnName("stock");
        });

        modelBuilder.Entity<Inventory>(entity =>
        {
            entity.ToTable("inventory");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Productid).HasColumnName("productid");
            entity.Property(e => e.Quantity).HasColumnName("quantity");
            entity.Property(e => e.MovementType).HasColumnName("movement_type");
            entity.Property(e => e.Reference).HasColumnName("reference");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.Notes).HasColumnName("notes");

            entity.HasOne(d => d.Product).WithMany(p => p.Inventories)
                .HasForeignKey(d => d.Productid)
                .HasConstraintName("FK_inventory_product");
        });

        modelBuilder.Entity<InventoryAudit>(entity =>
        {
            entity.ToTable("inventory_audit");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Inventoryid).HasColumnName("inventoryid");
            entity.Property(e => e.ChangeAmount).HasColumnName("change_amount");
            entity.Property(e => e.ChangeDate)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnType("datetime")
                .HasColumnName("change_date");

            entity.HasOne(d => d.Inventory).WithMany(p => p.InventoryAudits)
                .HasForeignKey(d => d.Inventoryid)
                .HasConstraintName("FK_inventory_audit_inventory");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.ToTable("users");

            entity.HasKey(e => e.UserId).HasName("PK_users");

            entity.HasIndex(e => e.Username, "IX_users_username").IsUnique();
            entity.HasIndex(e => e.Email, "IX_users_email").IsUnique();

            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("username");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("email");
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasColumnName("password_hash");
            entity.Property(e => e.FullName)
                .HasMaxLength(100)
                .HasColumnName("full_name");
            entity.Property(e => e.Role)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Cashier")
                .HasColumnName("role");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.LastLogin)
                .HasColumnType("datetime")
                .HasColumnName("last_login");
            entity.Property(e => e.LastUpdated)
                .HasColumnType("datetime")
                .HasColumnName("last_updated");
        });

        modelBuilder.Entity<UserSession>(entity =>
        {
            entity.ToTable("user_sessions");

            entity.HasKey(e => e.SessionId).HasName("PK_user_sessions");

            entity.HasIndex(e => e.Token, "IX_user_sessions_token").IsUnique();
            entity.HasIndex(e => e.UserId, "IX_user_sessions_user_id");

            entity.Property(e => e.SessionId).HasColumnName("session_id");
            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.Token)
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnName("token");
            entity.Property(e => e.LoginTime)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnType("datetime")
                .HasColumnName("login_time");
            entity.Property(e => e.LogoutTime)
                .HasColumnType("datetime")
                .HasColumnName("logout_time");
            entity.Property(e => e.IPAddress)
                .HasMaxLength(50)
                .HasColumnName("ip_address");
            entity.Property(e => e.UserAgent)
                .HasMaxLength(500)
                .HasColumnName("user_agent");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");

            entity.HasOne(d => d.User).WithMany(p => p.UserSessions)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_user_sessions_users");
        });

        modelBuilder.Entity<Customer>(entity =>
        {
            entity.ToTable("customers");

            entity.HasKey(e => e.CustomerId).HasName("PK_customers");

            entity.HasIndex(e => e.CustomerCode, "IX_customers_code").IsUnique();
            entity.HasIndex(e => e.Email, "IX_customers_email");
            entity.HasIndex(e => e.PhoneNumber, "IX_customers_phone");

            entity.Property(e => e.CustomerId).HasColumnName("customer_id");
            entity.Property(e => e.CustomerCode)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("customer_code");
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("first_name");
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("last_name");
            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .HasColumnName("email");
            entity.Property(e => e.PhoneNumber)
                .HasMaxLength(20)
                .HasColumnName("phone_number");
            entity.Property(e => e.Address)
                .HasMaxLength(255)
                .HasColumnName("address");
            entity.Property(e => e.City)
                .HasMaxLength(100)
                .HasColumnName("city");
            entity.Property(e => e.State)
                .HasMaxLength(100)
                .HasColumnName("state");
            entity.Property(e => e.ZipCode)
                .HasMaxLength(20)
                .HasColumnName("zip_code");
            entity.Property(e => e.Country)
                .HasMaxLength(100)
                .HasColumnName("country");
            entity.Property(e => e.TotalPurchases)
                .HasColumnType("decimal(18, 2)")
                .HasDefaultValue(0)
                .HasColumnName("total_purchases");
            entity.Property(e => e.TotalOutstanding)
                .HasColumnType("decimal(18, 2)")
                .HasDefaultValue(0)
                .HasColumnName("total_outstanding");
            entity.Property(e => e.DateOfBirth)
                .HasColumnType("date")
                .HasColumnName("date_of_birth");
            entity.Property(e => e.Gender)
                .HasMaxLength(10)
                .HasColumnName("gender");
            entity.Property(e => e.LoyaltyStatus)
                .HasMaxLength(50)
                .HasDefaultValue("Regular")
                .HasColumnName("loyalty_status");
            entity.Property(e => e.LoyaltyPoints)
                .HasDefaultValue(0)
                .HasColumnName("loyalty_points");
            entity.Property(e => e.Notes).HasColumnName("notes");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.LastUpdated)
                .HasColumnType("datetime")
                .HasColumnName("last_updated");
        });

        modelBuilder.Entity<SalesTransaction>(entity =>
        {
            entity.ToTable("sales_transactions");

            entity.HasKey(e => e.TransactionId).HasName("PK_sales_transactions");

            entity.HasIndex(e => e.TransactionCode, "IX_sales_transactions_code").IsUnique();
            entity.HasIndex(e => e.TransactionDate, "IX_sales_transactions_date");
            entity.HasIndex(e => e.UserId, "IX_sales_transactions_user");
            entity.HasIndex(e => e.CustomerId, "IX_sales_transactions_customer");
            entity.HasIndex(e => e.Status, "IX_sales_transactions_status");

            entity.Property(e => e.TransactionId).HasColumnName("transaction_id");
            entity.Property(e => e.TransactionCode)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("transaction_code");
            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.CustomerId).HasColumnName("customer_id");
            entity.Property(e => e.TransactionDate)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnType("datetime")
                .HasColumnName("transaction_date");
            entity.Property(e => e.SubTotal)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("subtotal");
            entity.Property(e => e.TaxAmount)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("tax_amount");
            entity.Property(e => e.TotalAmount)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("total_amount");
            entity.Property(e => e.PaymentMethod)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("payment_method");
            entity.Property(e => e.AmountTendered)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("amount_tendered");
            entity.Property(e => e.ChangeAmount)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("change_amount");
            entity.Property(e => e.DiscountAmount)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("discount_amount");
            entity.Property(e => e.Notes).HasColumnName("notes");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .HasDefaultValue("completed")
                .HasColumnName("status");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");

            entity.HasOne(d => d.User).WithMany(p => p.SalesTransactions)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_sales_transactions_users");

            entity.HasOne(d => d.Customer).WithMany(p => p.SalesTransactions)
                .HasForeignKey(d => d.CustomerId)
                .HasConstraintName("FK_sales_transactions_customers");
        });

        modelBuilder.Entity<TransactionItem>(entity =>
        {
            entity.ToTable("transaction_items");

            entity.HasKey(e => e.ItemId).HasName("PK_transaction_items");

            entity.HasIndex(e => e.TransactionId, "IX_transaction_items_transaction");
            entity.HasIndex(e => e.Productid, "IX_transaction_items_product");

            entity.Property(e => e.ItemId).HasColumnName("item_id");
            entity.Property(e => e.TransactionId).HasColumnName("transaction_id");
            entity.Property(e => e.Productid).HasColumnName("productid");
            entity.Property(e => e.Quantity).HasColumnName("quantity");
            entity.Property(e => e.UnitPrice)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("unit_price");
            entity.Property(e => e.DiscountPercent)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("discount_percent");
            entity.Property(e => e.DiscountAmount)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("discount_amount");
            entity.Property(e => e.LineTotal)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("line_total");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");

            entity.HasOne(d => d.SalesTransaction).WithMany(p => p.TransactionItems)
                .HasForeignKey(d => d.TransactionId)
                .HasConstraintName("FK_transaction_items_sales_transactions");

            entity.HasOne(d => d.Product).WithMany(p => p.TransactionItems)
                .HasForeignKey(d => d.Productid)
                .HasConstraintName("FK_transaction_items_product");
        });

        modelBuilder.Entity<PaymentMethod>(entity =>
        {
            entity.ToTable("payment_methods");

            entity.HasKey(e => e.PaymentMethodId).HasName("PK_payment_methods");

            entity.Property(e => e.PaymentMethodId).HasColumnName("payment_method_id");
            entity.Property(e => e.MethodName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("method_name");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
        });

        modelBuilder.Entity<BarcodeMapping>(entity =>
        {
            entity.ToTable("barcode_mapping");

            entity.HasKey(e => e.BarcodeId).HasName("PK_barcode_mapping");

            entity.HasIndex(e => e.Barcode, "IX_barcode_mapping_barcode").IsUnique();
            entity.HasIndex(e => e.Productid, "IX_barcode_mapping_product");

            entity.Property(e => e.BarcodeId).HasColumnName("barcode_id");
            entity.Property(e => e.Barcode)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("barcode");
            entity.Property(e => e.Productid).HasColumnName("productid");
            entity.Property(e => e.BarcodeType)
                .HasMaxLength(50)
                .HasColumnName("barcode_type");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");

            entity.HasOne(d => d.Product).WithMany(p => p.BarcodeMappings)
                .HasForeignKey(d => d.Productid)
                .HasConstraintName("FK_barcode_mapping_product");
        });

        modelBuilder.Entity<PaymentTenderLog>(entity =>
        {
            entity.ToTable("payment_tender_log");

            entity.HasKey(e => e.TenderId).HasName("PK_payment_tender_log");

            entity.HasIndex(e => e.TransactionId, "IX_payment_tender_log_transaction");

            entity.Property(e => e.TenderId).HasColumnName("tender_id");
            entity.Property(e => e.TransactionId).HasColumnName("transaction_id");
            entity.Property(e => e.PaymentMethod)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("payment_method");
            entity.Property(e => e.AmountReceived)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("amount_received");
            entity.Property(e => e.ChangeReturned)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("change_returned");
            entity.Property(e => e.PaymentStatus)
                .HasMaxLength(20)
                .HasColumnName("payment_status");
            entity.Property(e => e.PaymentReference)
                .HasMaxLength(100)
                .HasColumnName("payment_reference");
            entity.Property(e => e.Notes).HasColumnName("notes");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");

            entity.HasOne(d => d.SalesTransaction).WithMany(p => p.PaymentTenderLogs)
                .HasForeignKey(d => d.TransactionId)
                .HasConstraintName("FK_payment_tender_log_sales_transactions");
        });

        modelBuilder.Entity<DailySalesSummary>(entity =>
        {
            entity.ToTable("daily_sales_summary");

            entity.HasKey(e => e.SummaryId).HasName("PK_daily_sales_summary");

            entity.HasIndex(e => e.SummaryDate, "IX_daily_sales_summary_date").IsUnique();

            entity.Property(e => e.SummaryId).HasColumnName("summary_id");
            entity.Property(e => e.SummaryDate)
                .HasColumnType("date")
                .HasColumnName("summary_date");
            entity.Property(e => e.TotalSales)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("total_sales");
            entity.Property(e => e.TotalTax)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("total_tax");
            entity.Property(e => e.TotalDiscount)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("total_discount");
            entity.Property(e => e.TransactionCount).HasColumnName("transaction_count");
            entity.Property(e => e.ItemsSold).HasColumnName("items_sold");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
        });

        modelBuilder.Entity<Receipt>(entity =>
        {
            entity.ToTable("receipts");

            entity.HasKey(e => e.ReceiptId).HasName("PK_receipts");

            entity.HasIndex(e => e.TransactionId, "IX_receipts_transaction");
            entity.HasIndex(e => e.Status, "IX_receipts_status");
            entity.HasIndex(e => e.CreatedAt, "IX_receipts_created_at");

            entity.Property(e => e.ReceiptId).HasColumnName("receipt_id");
            entity.Property(e => e.TransactionId).HasColumnName("transaction_id");
            entity.Property(e => e.ReceiptNumber)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("receipt_number");
            entity.Property(e => e.RecipientEmail)
                .HasMaxLength(100)
                .HasColumnName("recipient_email");
            entity.Property(e => e.RecipientPhone)
                .HasMaxLength(20)
                .HasColumnName("recipient_phone");
            entity.Property(e => e.DeliveryMethod).HasColumnName("delivery_method"); // 0=Print, 1=Email, 2=SMS, 3=WhatsApp
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.SentAt)
                .HasColumnType("datetime")
                .HasColumnName("sent_at");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .HasDefaultValue("Pending")
                .HasColumnName("status");
            entity.Property(e => e.Notes)
                .HasColumnName("notes");

            entity.HasOne(d => d.SalesTransaction)
                .WithMany()
                .HasForeignKey(d => d.TransactionId)
                .HasConstraintName("FK_receipts_sales_transactions");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.ToTable("Roles");

            entity.HasKey(e => e.RoleId).HasName("PK_roles");

            entity.Property(e => e.RoleId).HasColumnName("RoleId");
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("RoleName");
            entity.Property(e => e.Description).HasColumnName("Description");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("IsActive");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnType("datetime2")
                .HasColumnName("CreatedAt");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime2")
                .HasColumnName("UpdatedAt");
        });

        modelBuilder.Entity<Permission>(entity =>
        {
            entity.ToTable("Permissions");

            entity.HasKey(e => e.PermissionId).HasName("PK_permissions");

            entity.Property(e => e.PermissionId).HasColumnName("PermissionId");
            entity.Property(e => e.PermissionCode)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("PermissionCode");
            entity.Property(e => e.PermissionName)
                .IsRequired()
                .HasMaxLength(150)
                .HasColumnName("PermissionName");
            entity.Property(e => e.Description).HasColumnName("Description");
            entity.Property(e => e.Module)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("Module");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("IsActive");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnType("datetime2")
                .HasColumnName("CreatedAt");
        });

        modelBuilder.Entity<RolePermission>(entity =>
        {
            entity.ToTable("RolePermissions");

            entity.HasKey(e => e.RolePermissionId).HasName("PK_role_permissions");

            entity.HasIndex(e => e.RoleId, "IX_role_permissions_role_id");
            entity.HasIndex(e => e.PermissionId, "IX_role_permissions_permission_id");

            entity.Property(e => e.RolePermissionId).HasColumnName("RolePermissionId");
            entity.Property(e => e.RoleId).HasColumnName("RoleId");
            entity.Property(e => e.PermissionId).HasColumnName("PermissionId");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnType("datetime2")
                .HasColumnName("CreatedAt");

            entity.HasOne(d => d.Role).WithMany(p => p.RolePermissions)
                .HasForeignKey(d => d.RoleId)
                .HasConstraintName("FK_RolePermissions_Roles");

            entity.HasOne(d => d.Permission).WithMany(p => p.RolePermissions)
                .HasForeignKey(d => d.PermissionId)
                .HasConstraintName("FK_RolePermissions_Permissions");
        });

        modelBuilder.Entity<AuditLog>(entity =>
        {
            entity.ToTable("AuditLogs");

            entity.HasKey(e => e.AuditLogId).HasName("PK_audit_logs");

            entity.HasIndex(e => e.UserId, "IX_audit_logs_user_id");
            entity.HasIndex(e => e.CreatedAt, "IX_audit_logs_created_at");

            entity.Property(e => e.AuditLogId).HasColumnName("AuditLogId");
            entity.Property(e => e.UserId).HasColumnName("UserId");
            entity.Property(e => e.Action)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("Action");
            entity.Property(e => e.Module)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("Module");
            entity.Property(e => e.EntityType)
                .HasMaxLength(100)
                .HasColumnName("EntityType");
            entity.Property(e => e.EntityId).HasColumnName("EntityId");
            entity.Property(e => e.OldValue).HasColumnName("OldValue");
            entity.Property(e => e.NewValue).HasColumnName("NewValue");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .HasColumnName("Status");
            entity.Property(e => e.IPAddress)
                .HasMaxLength(45)
                .HasColumnName("IPAddress");
            entity.Property(e => e.UserAgent)
                .HasMaxLength(500)
                .HasColumnName("UserAgent");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnType("datetime2")
                .HasColumnName("CreatedAt");

            entity.HasOne(d => d.User).WithMany()
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_AuditLogs_Users");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}