// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CrazyPOS.Server.Models;

public partial class HoldOrder
{
    public long Id { get; set; }

    public string CustomerName { get; set; }

    public DateTime OrderDate { get; set; }

    public string Status { get; set; }

    public decimal TotalAmount { get; set; }

    public virtual ICollection<HoldOrderItem> HoldOrderItems { get; set; } = new List<HoldOrderItem>();
}