// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CrazyPOS.Server.Models;

public partial class Product
{
    public long Productid { get; set; }

    public string Name { get; set; }

    public decimal? Price { get; set; }

    public long? Categoryid { get; set; }

    public int? Stock { get; set; }

    public byte[] Image { get; set; }

    public string Imgextension { get; set; }

    public string Barcode { get; set; }

    public string Description { get; set; }

    public virtual ICollection<HoldOrderItem> HoldOrderItems { get; set; } = new List<HoldOrderItem>();

    public virtual ICollection<Inventory> Inventories { get; set; } = new List<Inventory>();

    public virtual ICollection<TransactionItem> TransactionItems { get; set; } = new List<TransactionItem>();

    public virtual ICollection<BarcodeMapping> BarcodeMappings { get; set; } = new List<BarcodeMapping>();
}